tenant_name: prod_pci
app_name: banking_app
epgs:
  - name: web_epg
    bd: 192.168.11.0_24_bd
    prefGroup: no
    contracts:
      - contract: external_to_web_con
        type: consumer
      - contract: web_to_app_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg
  - name: app_epg
    bd: 192.168.12.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_db_con
        type: consumer
      - contract: web_to_app_con
        type: provider
      - contract: app_to_auth_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg
  - name: db_epg
    bd: 192.168.13.0_24_bd
    prefGroup: no
    contracts:
      - contract: cache_to_db_con
        type: provider
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg
  - name: db_cache_epg
    bd: 192.168.13.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_db_con
        type: provider
      - contract: cache_to_db_con
        type: consumer
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg
  - name: log_epg
    bd: 192.168.12.0_24_bd
    prefGroup: no
    contracts:
      - contract: any_to_log_con
        type: provider
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg
  - name: auth_epg
    bd: 192.168.12.0_24_bd
    prefGroup: no
    contracts:
      - contract: app_to_auth_con
        type: provider
      - contract: any_to_log_con
        type: consumer
    domains:
      - type: vmm
        provider: vmware
        domain: vmm_vds_mlg