# ACI playbook - Create HRMS App Demo

- name: Create HRMS App
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password | default(omit) }}"
      private_key: "{{ aci_private_key | default(omit) }}"
      certificate_name: "{{ aci_certificate_name | default(omit) }}"
      validate_certs: "{{ aci_validate_certs }}"
      annotation: "orchestrator:ansible"
      state: present
      output_path: dryrun_data.json

  vars_files:
    - hrms_app_variables.yaml

  tasks:
    - name: Add Tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        state: present

    - name: Add Application Profile
      cisco.aci.aci_ap:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        state: present

    - name: Add EPG
      cisco.aci.aci_epg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.name }}"
        bd: "{{ item.bd }}"
        preferred_group: "{{ item.prefGroup }}"
        state: present
      loop: "{{ epgs }}"

    - name: Add contracts
      cisco.aci.aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.0.name }}"
        contract: "{{ item.1.contract }}"
        contract_type: "{{ item.1.type }}"
        state: present
      loop: "{{ epgs | subelements('contracts') }}"

    - name: Add domain binding
      cisco.aci.aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.0.name }}"
        domain: "{{ item.1.name }}"
        domain_type: "{{ item.1.type }}"
        vm_provider: "{{ item.1.provider }}"
        deploy_immediacy: immediate
        resolution_immediacy: pre-provision
        state: present
      loop: "{{ epgs | subelements('domains') }}"

    # Contracts Definition

    - name: Add contracts
      cisco.aci.aci_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.name }}"
        description: "{{ item.descr }}"
        scope: "{{ item.scope }}"
        state: present
      loop: "{{ contracts }}"

    - name: Add contract subjects
      cisco.aci.aci_contract_subject:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.name }}"
        subject: "{{ item.subject }}"
        reverse_filter: "{{ item.reverse_filter }}"
        state: present
      loop: "{{ contracts }}"

    - name: Bind filters to contract subjects
      cisco.aci.aci_contract_subject_to_filter:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.0.name }}"
        subject: "{{ item.0.subject }}"
        filter: "{{ item.1 }}"
        log: log
        state: present
      loop: "{{ contracts | subelements('filters') }}"
